package com.api.marketplace.enums;

public enum Category {
    JAVA, JAVASCRIPT, PYTHON, CSHARP, RUBY, PHP, SWIFT, KOTLIN, GO, RUST,
    HTML, CSS, SQL, CPLUSPLUS, C, DART, SCALA, PERL, HASKELL, LISP,
    MATLAB, GROOVY, COBOL, FORTRAN, OBJECTIVEC, VISUALBASIC, ASSEMBLY,
    TYPESCRIPT, ELIXIR, CLOJURE, OCAML, FSHARP, LUA, PROLOG, SMALLTALK,
    ACTIONSCRIPT, ABAP, APEX, PLSQL, RPG, XQUERY, VHDL, VERILOG,
    SQLSERVER, MYSQL, POSTGRESQL, MONGODB, ORACLE, SQLITE, REDIS
}
